@startuml
class PrivateDocument {
  +read(): string
}

class SecureProxy {
  -document: PrivateDocument
  -password: string
  +read(password: string): string
}
SecureProxy --> PrivateDocument: Uses
@enduml