@startuml
                   class Tree { }
                   class TreeFactory {
                     +get_tree(name: String) : Tree
                   }
                   TreeFactory "1" -right- "n" Tree
                   @enduml